### ISSUE TITLE
Update Ruby Image on DockerFile

### ISSUE THREAD

**Issue by jonathanmullerr** [Purple-Stock/open-erp#17]
Fala pessoal! Tava dando uma olhada no projeto de vocês, animal!

Porém tentando subir o projeto localmente com o docker tive alguns problemas, e já achei a solução. Então apenas compartilhando aqui para melhoria do projeto.

### Problemas:

1. Versão do Ruby no DockerFile diferente da versão de ruby do projeto. 
Dockerfile = 3.1.2 | .ruby-verion = 3.2.2

2. Não sei se ocorre com todos, mas subindo pelo Docker tive uma trava com o yarn. Consegui resolver da seguinte maneira:
Troquei 
`RUN npm install --global yarn`

por

```
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -y yarn
```
  
De forma geral foi isso, mas também vou compartilhar algumas informações que tive que desenrolar aqui para subir localmente para quem sabe adicionar em alguma etapa de trobleshooting no readme

### Ausencia de docker-compose localmene
Seguir os passos

```
sudo apt update
sudo apt install curl
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version
```

### Criando DB Localmente:
```
sudo apt update
sudo apt install postgresql
sudo -i -u postgres
psql
CREATE DATABASE open_erp;
CREATE USER postgres WITH PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE open_erp TO postgres;

```
Com isso credenciais genéricas como abaixo devem funcionar =)

```
DB_HOST=open-erp-database-1
DATABASE_NAME=open_erp
DATABASE_USER=postgres
DATABASE_PASSWORD=postgres
DATABASE_PORT=5432
DATABASE_URL=postgres://postgres:postgres@open-erp-database-1:5432/open_erp
```

### Rodando Migrations e acessando o bash do container

Acessando o container do projeto para rodar comando rails:

```
# Para achar o id do container
docker ps

# Para acessar o container
docker exec -it <container_name_or_id> /bin/bash
```

Nesse caso acima ainda seria mais simples se fosse definido um nome para o container no docker-compose, como por exemplo

```
services:
  app:
    container_name: open-erp-app
    build:
      context: .
      dockerfile: Dockerfile
#    env_file:
#      - rails.env
    depends_on:
      - database
      - redis
    ports: 
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

```

Como é a primeira vez que acesso, acho que sempre é uma boa oportunidade para levantar esses pontos para facilitar mais pessoas contribuirem. Mas com um conhecimento técnico básico daria para chegar nessas soluções.

Estarei estudando as issues para tentar contribuir com algo. Porém vi que a maioria delas tem uma descrição bem vaga. De todo modo, fico a disposição para ajudar com alguma treta por aí
Só me chamar no Linkeding https://www.linkedin.com/in/mullerjon/
